name: 'ParaPy Application Release Action'
description: 'Action to release and deploy ParaPy Applications'
inputs:
  parapy-pypi-address:
    description: 'ParaPy PyPI python repository at which to obtain the ParaPy dependencies'
    required: false
    default: 'pypi.parapy.nl'
  parapy-pypi-username:
    description: 'user name for the ParaPy PyPI package repository'
    required: true
  parapy-pypi-password:
    description: 'password for the ParaPy PyPI package repository'
    required: true
  parapy-cloud-address:
    description: 'ParaPyCloud address that the Application should release to, this is likely your ParaPy company address, e.g. <company-name>.parapy.nl'
    required: true
  service-account-identifier:
    description: 'ParaPy service account identifier that has access to your application release within ParaPy Cloud'
    required: true
  service-account-secret:
    description: 'ParaPy service account secret of the ParaPy service account identifier supplied'
    required: true
  parapy-app-identifier:
    description: 'ParaPy Cloud application identifier of your ParaPy application'
    required: true
  parapy-app-version:
    description: 'The version of your application release, (e.g. 0.1.0, [semantic versioning](https://semver.org/)'
    required: true
  deploy:
    description: 'Whether to deploy after the release of your application is successful'
    required: false
    default: "false"
  parapy-cloud-cli-version:
    description: 'Version of parapy cloud cli, keep empty for the latest'
    required: false
    default: ""

branding:
  icon: 'plus-circle'
  color: 'blue'

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
        architecture: 'x64'

    - name: Install parapy-cloud-cli
      shell: bash
      run: >
        pip install parapy-cloud-cli${{ inputs.parapy-cloud-cli-version == "" && || ~= }}${{ inputs.parapy-cloud-cli-version }}
        --index-url https://${{ inputs.parapy-pypi-username }}:${{ inputs.parapy-pypi-password }}@${{ inputs.parapy-pypi-address }}/simple/

    - name: Building and releasing the application
      shell: bash
      run: >
        parapy cloud app release
        .
        --url ${{ inputs.parapy-cloud-address }}
        --client-id ${{ inputs.service-account-identifier }}
        --secret ${{ inputs.service-account-secret }}
        --version ${{ inputs.parapy-app-version }}
        --id ${{ inputs.parapy-app-identifier }}
        ${{ inputs.deploy == 'true' && '--deploy' || '' }}
