name: Release a new version of your application
on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'Application version to release (e.g. -> 0.1.0)'     
        required: true
      deploy:
        description: 'Whether to deploy the application if the release is successful'
        type: boolean
        default: false
      

jobs:
  application-release:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: parapydev app-release-action
        uses: ./
        with:
            license-key: ${{ secrets.PARAPY_LICENSE_KEY_1 }}
            license-certificate: ${{ secrets.PARAPY_LICENSE_KEY_2 }}
            parapy-pypi-username: ${{ vars.PARAPY_PYPI_USERNAME }}
            parapy-pypi-password: ${{ secrets.PARAPY_PYPI_PASSWORD }}
            parapy-cloud-address: "cloud.parapy.nl"
            service-account-identifier: ${{vars.PARAPY_SERVICE_ACCOUNT_CLIENT_ID }}
            service-account-secret: ${{vars.PARAPY_SERVICE_ACCOUNT_SECRET }}
            parapy-app-identifier: ${{vars.PARAPY_APP_ID }}
            parapy-app-version: ${{ inputs.version }}
            deploy: ${{ inputs.deploy }}
          